openapi: 3.0.0
info:
  title: Sample API 1
  version: 1.0.0
paths:
  /api/v1/resource1:
    get:
      summary: Get Resource 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
components:
  schemas:
    Resource1:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
