openapi: 3.0.0
info:
  title: Sample API 2
  version: 2.0.0
paths:
  /api/v2/resource2:
    post:
      summary: Create Resource 2
      requestBody:
        description: Resource 2 object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource2'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource2'
components:
  schemas:
    Resource2:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
